export const WORDS = [
  { original: 'CODE', hint: 'Набір інструкцій для комп\'ютера', level: 'normal' },
  { original: 'BUG', hint: 'Помилка в програмі', level: 'normal' },
  { original: 'JAVA', hint: 'Популярна мова програмування', level: 'normal' },
  { original: 'NODE', hint: 'Середовище виконання JS поза браузером', level: 'normal' },
  { original: 'LOOP', hint: 'Повторення коду (цикл)', level: 'normal' },
  { original: 'DATA', hint: 'Інформація, яку обробляє програма', level: 'normal' },
  { original: 'GIT', hint: 'Система контролю версій', level: 'normal' },
  { original: 'DOM', hint: 'Об\'єктна модель документа', level: 'normal' },
  { original: 'REACT', hint: 'Бібліотека для інтерфейсів', level: 'hard' },
  { original: 'PROMISE', hint: 'Об\'єкт для асинхронних операцій', level: 'hard' },
  { original: 'COMPONENT', hint: 'Будівельний блок React', level: 'hard' },
  { original: 'VARIABLE', hint: 'Іменоване сховище для даних', level: 'hard' },
  { original: 'FUNCTION', hint: 'Блок коду, який можна викликати', level: 'hard' },
  { original: 'BROWSER', hint: 'Програма для перегляду веб-сторінок', level: 'hard' },
  { original: 'RECURSION', hint: 'Функція викликає саму себе', level: 'hard' },
  { original: 'INTERFACE', hint: 'Місце взаємодії користувача з системою', level: 'hard' },
  { original: 'POLYMORPHISM', hint: 'Один інтерфейс, багато реалізацій', level: 'expert' },
  { original: 'ENCAPSULATION', hint: 'Приховування даних всередині об\'єкта', level: 'expert' },
  { original: 'ASYNCHRONOUS', hint: 'Виконання коду без блокування потоку', level: 'expert' },
  { original: 'MIDDLEWARE', hint: 'ПЗ посередник між запитом і відповіддю', level: 'expert' },
  { original: 'VIRTUALIZATION', hint: 'Створення віртуальної версії ресурсу', level: 'expert' },
  { original: 'AUTHENTICATION', hint: 'Перевірка справжності користувача', level: 'expert' },
  { original: 'MICROSERVICES', hint: 'Архітектура з маленьких незалежних сервісів', level: 'expert' }
];